// Mocks generated by Mockito 5.0.15 from annotations
// in equiz/test/modules/auth/infra/repositories/auth_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:equiz/modules/auth/domain/user_params.dart' as _i5;
import 'package:equiz/modules/auth/infra/datasources/auth_datasource_interface.dart'
    as _i3;
import 'package:equiz/modules/auth/infra/models/user_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeUserModel_0 extends _i1.Fake implements _i2.UserModel {}

/// A class which mocks [IAuthDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthDatasource extends _i1.Mock implements _i3.IAuthDatasource {
  MockIAuthDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> createAccount(_i5.UserParams? params) =>
      (super.noSuchMethod(Invocation.method(#createAccount, [params]),
              returnValue: Future<_i2.UserModel>.value(_FakeUserModel_0()))
          as _i4.Future<_i2.UserModel>);
  @override
  String toString() => super.toString();
}
